### ISSUE TITLE
Cannot find module './types.json'

### ISSUE THREAD

**Issue by arvindan** [broofa/node-mime#120]
I installed the module (fs, util, mime) in shared folder
written the below script 

``` javascript
var fs = require("fs"),
    util = require("util");

var mime = require("mime");

var dataUri = base64Image("/home/arvindan/testing/abc.jpg");
console.log(dataUri);

function base64Image(src) {
    var data = fs.readFileSync(src).toString("base64");
    return util.format("data:%s;base64,%s", mime.lookup(src), data);
}
```

on execution throwing below error
Error: Cannot find module './types.json'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/arvindan/node_modules/mime/mime.js:87:13)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)

please help me to resolve the issue

**Comment by broofa** [comment]
I'm unable to reproduce this.

```
kieffer@Roberts-MacBook-Pro$ npm install -g mime
/Users/kieffer/local/node/bin/mime -> /Users/kieffer/local/node/lib/node_modules/mime/cli.js
mime@1.3.4 /Users/kieffer/local/node/lib/node_modules/mime

kieffer@Roberts-MacBook-Pro$ node -e "console.log(require('mime').lookup('txt'))"
text/plain

kieffer@Roberts-MacBook-Pro$
```

**Comment by whitlockjc** [comment]
I just reproduced this exact same error using Express 4.x:

```
Error: Cannot find module './types.json'
   at Function.Module._resolveFilename (module.js:338:15)
   at Function.Module._load (module.js:280:25)
   at Module.require (module.js:364:17)
   at require (module.js:380:17)
   at Object.<anonymous> (/Users/notyou/projects/myproject/node_modules/express/node_modules/send/node_modules/mime/mime.js:87:13)
   at Module._compile (module.js:456:26)
   at Object.Module._extensions..js (module.js:474:10)
   at Module.load (module.js:356:32)
   at Function.Module._load (module.js:312:12)
   at Module.require (module.js:364:17)
```

I'm working on getting more details but for now, at least @arvindan doesn't have to worry about being alone.  ;)

**Comment by arvindan** [comment]
Thanks
 


     On Tuesday, 31 March 2015 7:40 AM, Jeremy Whitlock <notifications@github.com> wrote:
   

 I just reproduced this exact same error using Express 4.x:Error: Cannot find module './types.json'
   at Function.Module._resolveFilename (module.js:338:15)
   at Function.Module._load (module.js:280:25)
   at Module.require (module.js:364:17)
   at require (module.js:380:17)
   at Object.<anonymous> (/Users/notyou/projects/myproject/node_modules/express/node_modules/send/node_modules/mime/mime.js:87:13)
   at Module._compile (module.js:456:26)
   at Object.Module._extensions..js (module.js:474:10)
   at Module.load (module.js:356:32)
   at Function.Module._load (module.js:312:12)
   at Module.require (module.js:364:17)
I'm working on getting more details but for now, at least @arvindan doesn't have to worry about being alone. ;)—

**Comment by jpv** [comment]
same error for me.
No ./type.js anywhere....
Error: Cannot find module './types.json'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/home/jpv/dsn-cockpit-pm2/dsn-cockpit/dsn-cockpit-server/node_modules/express/node_modules/send/node_modules/mime/mime.js:87:13)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)

**Comment by whitlockjc** [comment]
Node.js v0.10 on the server where this was reproduced for me.  Still trying to get more details.

**Comment by olalonde** [comment]
Why is `types.json` gitignored?

**Comment by broofa** [comment]
@olalonde `types.json` is built as part of the prepublish step, so technically isn't required as part of the source repo.  That said, that entry in .gitignore was removed in a80fa147ce33a6ee23336542ff855fa5b3036e07, which I apparently hadn't pushed.  I've remedied that but I don't think that's related to this issue.

@jpv @whitlockjc the common thread here is the `send` module... which includes the mime-v1.3.4.  I've installed express latest and verified that `require('express')` triggers a call to `require('send')` and subsequently `require('mime')` but I still can't repro on my system. :frowning:  Here's the detailed version of what I tested: https://gist.github.com/broofa/b08d4812371193b7a114

@arvindan I tried [unsuccessfully] to repro your bug again. Still no luck.  Here's the console log: https://gist.github.com/broofa/ecb06e3daef52ef9c713

Can the three of you try these same steps and let me know what happens?  Also note if you're running different versions of npm/node, please.

**Comment by qazedx** [comment]
any news on this? I am struggling with this error for 2 days now, I am using:

node -v
v0.10.25

npm -v
1.4.21

```javascript
"dependencies": {
	"peerjs": "0.3.10",
	"express": "4.3.1",
	"node-static": "0.7.6",
	"ws": "0.4.25",
	"underscore": "1.4.4",
	"gl-matrix": "2.2.1"
    },
```


I am on xubuntu 15.04, haven't had any problems when I worked on win 7, switched to linux just recently.

**Comment by kevinnsun** [comment]
I had this same problem when trying to run karma after installing various modules (http-errors, utils-merge, etc) I fixed the problem by updating/ reintsalling karma globally using "npm install karma -g"

**Comment by HiKat** [comment]
I fixed this error with ```$ npm install mime```.

**Comment by huangbxaaa** [comment]
Try
```
rm -rf node_modules
npm install -g npm@latest
npm i core-util-is
```
